services:
  docs:
    image: satcomx00/custom-doc-website:latest
    container_name: vitepress-docs
    ports:
      - "0.0.0.0:5173:5173"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_LABEL_ENABLE=true
      - TZ=Europe/Paris
    labels:
      - "com.centurylinklabs.watchtower.enable=false"